# -*- coding: gb18030 -*-
from bwdebug import *
import ResMgr
import BigWorld
import md5

space_sub_dir = ['chang_jing_wu_jian', 'deng_lu', 'di_biao', 'dong_hai_zhu_dao', 'fengmingguo', 'feng_ming_cheng', 'fu_ben_bang_hui_ling_di', 'fu_ben_bang_hui_zhan_chang_01', 'fu_ben_bang_hui_zhan_chang_02', 'fu_ben_bang_hui_zhan_chang_03', 'fu_ben_bang_hui_zhan_chang_04', 'fu_ben_bang_hui_zhan_chang_05', 'fu_ben_chang_jing_jue_se', 'fu_ben_dao_yu', 'fu_ben_jian_yu', 'fu_ben_lin_di', 'fu_ben_long_qi_dong', 'fu_ben_npc_zheng_duo_zhan', 'fu_ben_shan_ding', 'fu_ben_shan_gu', 'fu_ben_shi_di', 'fu_ben_tian_guan', 'fu_ben_tian_guan_02', 'fu_ben_wu_dao_da_hui', 'fu_ben_wu_ran_shui_jing', 'fu_ben_wu_tai_001', 'fu_ben_xuan_tian_huan_jie', 'fu_ben_zheng_jiu_ya_yu', 'peng_lai', 'qian_neng_fu_ben_01', 'qian_neng_fu_ben_02', 'qian_neng_fu_ben_03', 'ri_guang_yu', 'sai_ma_chang_03', 'tong_yong', 'xin_shou_cun', 'yun_meng_ze', 'zhi_wu', 'zhu_lu_yuan']

space_file_mapping = {
		'chang_jing_wu_jian' : ('66eddc2b11964961bb10da4330ad5f43', ['space/chang_jing_wu_jian/maps/ty_011.dds', 'space/chang_jing_wu_jian/maps/ty_guan_mu_002.dds', 'space/chang_jing_wu_jian/maps/ty_lan_mo_gu_001.dds', 'space/chang_jing_wu_jian/maps/ty_ni_tan_001.dds', 'space/chang_jing_wu_jian/maps/ty_076.dds', 'space/chang_jing_wu_jian/maps/ty_shu_gan_001.dds', 'space/chang_jing_wu_jian/maps/ty_006.dds', 'space/chang_jing_wu_jian/maps/ty_077.dds', 'space/chang_jing_wu_jian/maps/ty_gou_wei_cao.dds', 'space/chang_jing_wu_jian/maps/ty_xian_he_001.dds']),
		'deng_lu' : ('e2facf90ee0966f9b99697e551f84770', ['space/deng_lu/zhi_wu/maps/zly_040.dds', 'space/deng_lu/wu_jian/maps/fmc_063.dds', 'space/deng_lu/zhi_wu/maps/zly_030.dds', 'space/deng_lu/wu_jian/maps/fmc_053.dds', 'space/deng_lu/wu_jian/maps/fmc_042.dds', 'space/deng_lu/wu_jian/maps/fmc_058.dds', 'space/deng_lu/wu_jian/maps/fmc_004.dds', 'space/deng_lu/wu_jian/maps/fmc_034.dds', 'space/deng_lu/wu_jian/maps/fmc_079.dds', 'space/deng_lu/zhi_wu/maps/zly_027.dds']),
		'di_biao' : ('cbb51d9e27412cb88d61f9342e1a23a5', ['space/di_biao/maps/cao_di_0045.dds', 'space/di_biao/maps/yan_shi_0014.dds', 'space/di_biao/maps/cao_di_0115.dds', 'space/di_biao/maps/tu_di_0004.dds', 'space/di_biao/maps/cao_di_0017.dds', 'space/di_biao/maps/sha_di_0013.dds', 'space/di_biao/maps/shi_di_0001.dds', 'space/di_biao/maps/cao_di_0111.dds', 'space/di_biao/maps/cao_di_0035.dds', 'space/di_biao/maps/ymz_shua_ping_cao_03.dds']),
		'dong_hai_zhu_dao' : ('6b1e018c9c493088f04e56efb9db4caf', ['space/dong_hai_zhu_dao/wu_jian/maps/fmc_113.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_062.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fm_zhi_wu_044.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_075.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_058.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fm_zhi_wu_037.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_063.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_010.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_087.dds', 'space/dong_hai_zhu_dao/wu_jian/maps/fmc_057.dds']),
		'fengmingguo' : ('2a2fb620d077add730b9983c21c387f6', ['space/fengmingguo/wu_jian/maps/fmc_123.dds', 'space/fengmingguo/wu_jian/maps/fmc_197.dds', 'space/fengmingguo/zhi_wu/maps/fm_zhi_wu_065.dds', 'space/fengmingguo/wu_jian/maps/fmc_136.dds', 'space/fengmingguo/wu_jian/maps/fmc_254.dds', 'space/fengmingguo/zhi_wu/maps/fm_zhi_wu_021.dds', 'space/fengmingguo/wu_jian/maps/fmc_003.dds', 'space/fengmingguo/wu_jian/maps/fmc_004.dds', 'space/fengmingguo/zhi_wu/maps/fm_zhi_wu_078.dds', 'space/fengmingguo/wu_jian/maps/fmc_063.dds']),
		'feng_ming_cheng' : ('fe9531d4650c01245ca25159c4df9b58', ['space/feng_ming_cheng/wu_jian/maps/xfm_051.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_237.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_187.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_058.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_182.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_175.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_014.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_223.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_159.dds', 'space/feng_ming_cheng/wu_jian/maps/xfm_094.dds']),
		'fu_ben_bang_hui_ling_di' : ('d3de7e92e5ad057372f3e1c61d50e0e7', ['space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_049.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_156.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_054.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_035.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_028.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_008.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_160.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_121.dds', 'space/fu_ben_bang_hui_ling_di/zhi_wu/maps/fb10_zhi_wu_007.dds', 'space/fu_ben_bang_hui_ling_di/wu_jian/maps/fb10_025.dds']),
		'fu_ben_bang_hui_zhan_chang_01' : ('1a289f5b4a370b95ce63ea03307002d0', ['space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_017.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_026.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_023.dds', 'space/fu_ben_bang_hui_zhan_chang_01/wu_jian/maps/zc01_004.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_034.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_011.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_012.dds', 'space/fu_ben_bang_hui_zhan_chang_01/wu_jian/maps/zc01_014.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_020.dds', 'space/fu_ben_bang_hui_zhan_chang_01/zhi_wu/maps/zc01_zhi_wu_007.dds']),
		'fu_ben_bang_hui_zhan_chang_02' : ('ebbdedf880a83d9af369db500145e236', ['space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_019.dds', 'space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_012.dds', 'space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_009.dds', 'space/fu_ben_bang_hui_zhan_chang_02/zhi_wu/maps/zc02_zhi_wu_009.dds', 'space/fu_ben_bang_hui_zhan_chang_02/zhi_wu/maps/zc02_zhi_wu_019.dds', 'space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_008.dds', 'space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_016.dds', 'space/fu_ben_bang_hui_zhan_chang_02/zhi_wu/maps/zc02_zhi_wu_001.dds', 'space/fu_ben_bang_hui_zhan_chang_02/wu_jian/maps/zc02_007.dds', 'space/fu_ben_bang_hui_zhan_chang_02/zhi_wu/maps/zc02_zhi_wu_003.dds']),
		'fu_ben_bang_hui_zhan_chang_03' : ('37f610adc12f18b63ba1ff7b468ca761', ['space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_009.dds', 'space/fu_ben_bang_hui_zhan_chang_03/zhi_wu/maps/zc03_zhi_wu_002.dds', 'space/fu_ben_bang_hui_zhan_chang_03/zhi_wu/maps/zc03_zhi_wu_017.dds', 'space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_022.dds', 'space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_025.dds', 'space/fu_ben_bang_hui_zhan_chang_03/zhi_wu/maps/zc03_zhi_wu_016.dds', 'space/fu_ben_bang_hui_zhan_chang_03/zhi_wu/maps/zc03_zhi_wu_008.dds', 'space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_019.dds', 'space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_005.dds', 'space/fu_ben_bang_hui_zhan_chang_03/wu_jian/maps/zc03_014.dds']),
		'fu_ben_bang_hui_zhan_chang_04' : ('e7f0e7ac02b6f09ec2336e806620b279', ['space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_006.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_019.dds', 'space/fu_ben_bang_hui_zhan_chang_04/zhi_wu/maps/zc04_zhi_wu_020.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_031.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_015.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_007.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_029.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_035.dds', 'space/fu_ben_bang_hui_zhan_chang_04/wu_jian/maps/zc04_042.dds', 'space/fu_ben_bang_hui_zhan_chang_04/zhi_wu/maps/zc04_zhi_wu_009.dds']),
		'fu_ben_bang_hui_zhan_chang_05' : ('105bd997f6e9183737d9bf5fc5befe2a', ['space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_016.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_022.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_014.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_013.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_015.dds', 'space/fu_ben_bang_hui_zhan_chang_05/zhi_wu/maps/zc05_zhi_wu_018.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_001.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_020.dds', 'space/fu_ben_bang_hui_zhan_chang_05/zhi_wu/maps/zc05_zhi_wu_010.dds', 'space/fu_ben_bang_hui_zhan_chang_05/wu_jian/maps/zc05_018.dds']),
		'fu_ben_chang_jing_jue_se' : ('b643e553fd119cf24cda9a678a940a4b', ['space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_002.dds', 'space/fu_ben_chang_jing_jue_se/zhi_wu/maps/fb_cjjs_zhi_wu_012.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_009.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_045.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_043.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_049.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_027.dds', 'space/fu_ben_chang_jing_jue_se/zhi_wu/maps/fb_cjjs_zhi_wu_009.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_020.dds', 'space/fu_ben_chang_jing_jue_se/wu_jian/maps/fb_cjjs_050.dds']),
		'fu_ben_dao_yu' : ('a008644c11d376bca32b226477d75cbc', ['space/fu_ben_dao_yu/wu_jian/maps/fb05_019.dds', 'space/fu_ben_dao_yu/zhi_wu/maps/fb05_zhi_wu_030.dds', 'space/fu_ben_dao_yu/wu_jian/maps/fb05_010.dds', 'space/fu_ben_dao_yu/zhi_wu/maps/fb05_zhi_wu_011.dds', 'space/fu_ben_dao_yu/wu_jian/maps/fb05_031.dds', 'space/fu_ben_dao_yu/zhi_wu/maps/fb05_zhi_wu_009.dds', 'space/fu_ben_dao_yu/wu_jian/maps/fb05_009.dds', 'space/fu_ben_dao_yu/wu_jian/maps/fb05_017.dds', 'space/fu_ben_dao_yu/zhi_wu/maps/fb05_zhi_wu_026.dds', 'space/fu_ben_dao_yu/zhi_wu/maps/fb05_zhi_wu_019.dds']),
		'fu_ben_jian_yu' : ('5ae4fbeaf0b7b173980c3b6af1c25384', ['space/fu_ben_jian_yu/wu_jian/maps/fb_jy_036.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_041.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_029.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_007.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_011.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_003.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_033.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_035.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_025.dds', 'space/fu_ben_jian_yu/wu_jian/maps/fb_jy_012.dds']),
		'fu_ben_lin_di' : ('89439d1bcd078d5a8dc43f53437e165a', ['space/fu_ben_lin_di/zhi_wu/maps/fb01_zhi_wu_002.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_010.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_015.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_025.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_012.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_009.dds', 'space/fu_ben_lin_di/zhi_wu/maps/fb01_zhi_wu_020.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_019.dds', 'space/fu_ben_lin_di/zhi_wu/maps/fb01_zhi_wu_017.dds', 'space/fu_ben_lin_di/wu_jian/maps/fb01_024.dds']),
		'fu_ben_long_qi_dong' : ('b12e5eeb49ef427c9d761190d2345c78', ['space/fu_ben_long_qi_dong/wu_jian/maps/lqd_050.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_038.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_016.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_043.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_037.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_009.dds', 'space/fu_ben_long_qi_dong/zhi_wu/maps/lqd_zhi_wu_029.dds', 'space/fu_ben_long_qi_dong/zhi_wu/maps/lqd_zhi_wu_013.dds', 'space/fu_ben_long_qi_dong/wu_jian/maps/lqd_031.dds', 'space/fu_ben_long_qi_dong/zhi_wu/maps/lqd_zhi_wu_035.dds']),
		'fu_ben_npc_zheng_duo_zhan' : ('32282f7e9876baccf361fddb52b55f63', ['space/fu_ben_npc_zheng_duo_zhan/wu_jian/maps/fb09_008.dds', 'space/fu_ben_npc_zheng_duo_zhan/zhi_wu/maps/fb09_zhi_wu_015.dds', 'space/fu_ben_npc_zheng_duo_zhan/zhi_wu/maps/fb09_zhi_wu_007.dds', 'space/fu_ben_npc_zheng_duo_zhan/wu_jian/maps/fb09_007.dds', 'space/fu_ben_npc_zheng_duo_zhan/zhi_wu/maps/fb09_zhi_wu_002.dds', 'space/fu_ben_npc_zheng_duo_zhan/wu_jian/maps/fb09_002.dds', 'space/fu_ben_npc_zheng_duo_zhan/zhi_wu/maps/fb09_zhi_wu_013.dds', 'space/fu_ben_npc_zheng_duo_zhan/zhi_wu/maps/fb09_zhi_wu_023.dds', 'space/fu_ben_npc_zheng_duo_zhan/wu_jian/maps/fb09_001.dds', 'space/fu_ben_npc_zheng_duo_zhan/wu_jian/maps/fb09_003.dds']),
		'fu_ben_shan_ding' : ('da498a23090cefcf67f3cfa050c49482', ['space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_021.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_016.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_007.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_002.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_010.dds', 'space/fu_ben_shan_ding/wu_jian/maps/fb02_003.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_024.dds', 'space/fu_ben_shan_ding/zhi_wu/maps/fb02_zhi_wu_008.dds', 'space/fu_ben_shan_ding/wu_jian/maps/fb02_004.dds', 'space/fu_ben_shan_ding/wu_jian/maps/fb02_008.dds']),
		'fu_ben_shan_gu' : ('4757bbe0507756b34f07e6341c181049', ['space/fu_ben_shan_gu/wu_jian/maps/fb03_006.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_017.dds', 'space/fu_ben_shan_gu/wu_jian/maps/fb03_010.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_032.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_005.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_026.dds', 'space/fu_ben_shan_gu/wu_jian/maps/fb03_007.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_024.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_001.dds', 'space/fu_ben_shan_gu/zhi_wu/maps/fb03_zhi_wu_013.dds']),
		'fu_ben_shi_di' : ('5d4b2d82afb75dbfe96732908ea3c02b', ['space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_014.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_011.dds', 'space/fu_ben_shi_di/wu_jian/maps/fb04_018.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_022.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_031.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_008.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_021.dds', 'space/fu_ben_shi_di/wu_jian/maps/fb04_024.dds', 'space/fu_ben_shi_di/zhi_wu/maps/fb04_zhi_wu_013.dds', 'space/fu_ben_shi_di/wu_jian/maps/fb04_015.dds']),
		'fu_ben_tian_guan' : ('3610aaa02fb714e77241d7f51332426a', ['space/fu_ben_tian_guan/wu_jian/maps/fb06_107.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_117.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_144.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_038.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_055.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_003.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_017.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_073.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_071.dds', 'space/fu_ben_tian_guan/wu_jian/maps/fb06_104.dds']),
		'fu_ben_tian_guan_02' : ('ba72922601b768117eb09eaacd225fc1', ['space/fu_ben_tian_guan_02/wu_jian/maps/fb07_043.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_048.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_034.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_018.dds', 'space/fu_ben_tian_guan_02/zhi_wu/maps/fb07_zhi_wu_001.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_083.dds', 'space/fu_ben_tian_guan_02/zhi_wu/maps/fb07_zhi_wu_010.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_064.dds', 'space/fu_ben_tian_guan_02/wu_jian/maps/fb07_001.dds', 'space/fu_ben_tian_guan_02/zhi_wu/maps/fb07_zhi_wu_007.dds']),
		'fu_ben_wu_dao_da_hui' : ('a0d6d263a44084ba10aab8a4642c57fd', ['space/fu_ben_wu_dao_da_hui/zhi_wu/maps/fb11_zhi_wu_013.dds', 'space/fu_ben_wu_dao_da_hui/zhi_wu/maps/fb11_zhi_wu_014.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_002.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_016.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_019.dds', 'space/fu_ben_wu_dao_da_hui/zhi_wu/maps/fb11_zhi_wu_010.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_050.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_012.dds', 'space/fu_ben_wu_dao_da_hui/zhi_wu/maps/fb11_zhi_wu_009.dds', 'space/fu_ben_wu_dao_da_hui/wu_jian/maps/fb11_018.dds']),
		'fu_ben_wu_ran_shui_jing' : ('44f4df506a50c6a519901ba24263ca8d', ['space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_006.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_033.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_020.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_018.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_004.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_013.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_015.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_017.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_022.dds', 'space/fu_ben_wu_ran_shui_jing/wu_jian/maps/fb12_003.dds']),
		'fu_ben_wu_tai_001' : ('6f4861b896ca05800cdc491979494034', ['space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_031.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_011.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_022.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_009.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_056.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_046.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_038.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_012.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_035.dds', 'space/fu_ben_wu_tai_001/wu_jian/maps/fb_wt_042.dds']),
		'fu_ben_xuan_tian_huan_jie' : ('a58226106c36d0eb6a642a9e98745650', ['space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_014.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_003.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_015.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_033.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_031.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_025.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_030.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_016.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_021.dds', 'space/fu_ben_xuan_tian_huan_jie/wu_jian/maps/fb08_026.dds']),
		'fu_ben_zheng_jiu_ya_yu' : ('e1b827caa3d7205834248b7a20374b6d', ['space/fu_ben_zheng_jiu_ya_yu/zhi_wu/maps/fb_yy_zhi_wu_016.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_013.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_015.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_006.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_012.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_009.dds', 'space/fu_ben_zheng_jiu_ya_yu/wu_jian/maps/fb_yy_001.dds', 'space/fu_ben_zheng_jiu_ya_yu/zhi_wu/maps/fb_yy_zhi_wu_001.dds', 'space/fu_ben_zheng_jiu_ya_yu/zhi_wu/maps/fb_yy_zhi_wu_010.dds', 'space/fu_ben_zheng_jiu_ya_yu/zhi_wu/maps/fb_yy_zhi_wu_013.dds']),
		'peng_lai' : ('a2ee8db124cf76ecdf5d14eba561f245', ['space/peng_lai/wu_jian/maps/pl_037.dds', 'space/peng_lai/zhi_wu/maps/pl_zhi_wu_038.dds', 'space/peng_lai/wu_jian/maps/pl_065.dds', 'space/peng_lai/wu_jian/maps/pl_029.dds', 'space/peng_lai/wu_jian/maps/pl_007.dds', 'space/peng_lai/zhi_wu/maps/pl_zhi_wu_031.dds', 'space/peng_lai/wu_jian/maps/pl_138.dds', 'space/peng_lai/wu_jian/maps/pl_119.dds', 'space/peng_lai/zhi_wu/maps/pl_zhi_wu_046.dds', 'space/peng_lai/wu_jian/maps/pl_053.dds']),
		'qian_neng_fu_ben_01' : ('b487dfda00beb8edc5b44cbabb128e0a', ['space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 07.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 20.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 14.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 01.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 41.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 42.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 08.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 04.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 17.dds', 'space/qian_neng_fu_ben_01/wu_jian/maps/QNFB_ 38.dds']),
		'qian_neng_fu_ben_02' : ('cddc5d812efb7c11e79e199ff7fc039d', ['space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_001.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_020.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_033.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_057.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_070.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_049.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_018.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_016.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_010.dds', 'space/qian_neng_fu_ben_02/wu_jian/maps/QNFB_039.dds']),
		'qian_neng_fu_ben_03' : ('1e94ebc38565c9e79be7ff64c19b40c0', ['space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_025.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_053.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_045.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_039.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_064.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_005.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_010.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_067.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_054.dds', 'space/qian_neng_fu_ben_03/wu_jian/maps/QNFB_065.dds']),
		'ri_guang_yu' : ('b3625f72037d10d8bcdc5b3c547aa38d', ['space/ri_guang_yu/zhi_wu/maps/rgy_zhi_wu_020.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_075.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_021.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_126.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_131.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_056.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_099.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_093.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_060.dds', 'space/ri_guang_yu/wu_jian/maps/rgy_029.dds']),
		'sai_ma_chang_03' : ('5fb589f9c4e7659ce4e4d825922c6bc6', ['space/sai_ma_chang_03/wu_jian/maps/smc_048.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_002.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_006.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_018.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_029.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_030.dds', 'space/sai_ma_chang_03/wu_jian/maps/smc_003.dds', 'space/sai_ma_chang_03/wu_jian/maps/smc_007.dds', 'space/sai_ma_chang_03/wu_jian/maps/smc_005.dds', 'space/sai_ma_chang_03/zhi_wu/maps/smc_zhi_wu_009.dds']),
		'tong_yong' : ('bd63efeec9c1dfd8bdb13ed49dbe844b', ['space/tong_yong/za_wu/maps/ty_xiang_lu_001.dds', 'space/tong_yong/za_wu/maps/ty_jiu_tan_002.dds', 'space/tong_yong/za_wu/maps/ty_085.dds', 'space/tong_yong/za_wu/maps/ty_047.dds', 'space/tong_yong/zhe_dang_pian/zhe_dang_pian_01.dds', 'space/tong_yong/za_wu/maps/ty_pu_tuan_002.dds', 'space/tong_yong/za_wu/maps/ty_pen_jing_002.dds', 'space/tong_yong/za_wu/maps/ty_084.dds', 'space/tong_yong/za_wu/maps/ty_shang_pin_025.dds', 'space/tong_yong/za_wu/maps/ty_shen_ta_001.dds']),
		'xin_shou_cun' : ('2bec16f71924fc942d7e18a33f739bb5', ['space/xin_shou_cun/wu_jian/maps/xsc_043.dds', 'space/xin_shou_cun/zhi_wu/maps/xsc_zhi_wu_003.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_032.dds', 'space/xin_shou_cun/zhi_wu/maps/xsc_zhi_wu_010.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_001.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_020.dds', 'space/xin_shou_cun/zhi_wu/maps/xsc_zhi_wu_006.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_024.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_009.dds', 'space/xin_shou_cun/wu_jian/maps/xsc_012.dds']),
		'yun_meng_ze' : ('5faa24f9a7d40d28c10de715afb4a4fa', ['space/yun_meng_ze/wu_jian/maps/ymz_146.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_006.dds', 'space/yun_meng_ze/zhi_wu/maps/ymz_zhi_wu_025.dds', 'space/yun_meng_ze/zhi_wu/maps/ymz_zhi_wu_065.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_111.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_007.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_045.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_033.dds', 'space/yun_meng_ze/wu_jian/maps/ymz_149.dds', 'space/yun_meng_ze/zhi_wu/maps/ymz_zhi_wu_040.dds']),
		'zhu_lu_yuan' : ('441e4559def774ac7155e22d9d109aed', ['space/zhu_lu_yuan/wu_jian/maps/zly_jz_081.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_136.dds', 'space/zhu_lu_yuan/zhi_wu/maps/zyl_066.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_031.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_234.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_002.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_168.dds', 'space/zhu_lu_yuan/wu_jian/maps/zly_jz_312.dds', 'space/zhu_lu_yuan/zhi_wu/maps/zly_025.dds', 'space/zhu_lu_yuan/zhi_wu/maps/zly_035.dds']),
}

def checkSpaceData( dir ):
	try:
		md5Val, files = space_file_mapping[dir]
	except KeyError:
		ERROR_MSG( "files check fault. err code 1." )
		return False

	md5Inst = md5.md5( "" )
	for filename in files:
		section = ResMgr.openSection( filename )
		if section is None:
			ERROR_MSG( "files check fault. err code 2." )
			return False

		md5Inst.update( section.asBinary )

	return md5Inst.hexdigest() == md5Val

def checkCurrentSpaceData():
	pl = BigWorld.player()
	if not hasattr( pl, "spaceID" ):
		return True

	d = BigWorld.getSpaceDataFirstForKey( pl.spaceID, 1 )
	try:
		p = d.rsplit( "?", 1 )[1]
	except:
		# 对于取地图失败的现象，我们只能认为这个是对的，否则玩家进不了游戏就麻烦大了
		return True

	section = ResMgr.openSection( p + "/config.xml" )
	if section is None:
		ERROR_MSG( "files check fault. err code 20." )
		return False

	modelPath = section.readString( "modelPath" )
	return checkSpaceData( modelPath )

def checkAllSpaceDirByConf():
	# 取得所有地图名
	for key in ResMgr.openSection( "universes" ).keys():
		if key[0] == ".": continue
		# 从地图名中读取config.xml文件
		p = key + "/config.xml"
		section = ResMgr.openSection( p )
		if section is None:
			ERROR_MSG( "files check fault. err code 31. " + p )
			return False
		# 根据config.xml中的"modelPath"值寻找相匹配的测试数据，并进行测试
		modelPath = section.readString( "modelPath" )
		if checkSpaceData( modelPath ):
			return False
	return True

def checkAllSpaceData():
	for dir in space_sub_dir:
		if not checkSpaceData( dir ):
			return False
	return True

def checkAllSpaceDir():
	s = "space/%s"
	for dir in space_sub_dir:
		section = ResMgr.openSection( s % dir )
		if section is None:
			return False
		if len( section.keys() ) == 0:
			return False
	return True

